-- AlterTable
ALTER TABLE "OrderAfterPay" ALTER COLUMN "birthdate" DROP NOT NULL,
ALTER COLUMN "location" DROP NOT NULL,
ALTER COLUMN "illnesses" DROP NOT NULL,
ALTER COLUMN "health_state" DROP NOT NULL,
ALTER COLUMN "aims" DROP NOT NULL,
ALTER COLUMN "hebits" DROP NOT NULL,
ALTER COLUMN "about_photos" DROP NOT NULL;
