import { ProductT } from "../../modules/products/interfaces/product";

export const productMock: ProductT[] = [
  {
    id: "b9c525a3-ab3a-11ec-80e2-005056015f74",
    sku: "233575",
    name: "ANTI-AGE Спирулина 1000 мг табл 1,1 г х100",
    vendor: "Эвалар",
    dosage: "1,1 г х100",
    country: "Россия",
    model: "таблетки",
    activeIngredient: null,
    regularPrice: 796,
    salePrice: null,
    inStock: true,
    quantity: 14,
    discount: null,
    images: ["/mockImages/product.png"],
    description: null,
    descriptionSections: [],
    shortDescription: null,
    permalink: null,
    attributes: [],
    groupedProducts: [],
    relatedIds: [],
    tags: [],
    analogs: [],
    variations: [],
    isFeatured: false,
    category: null,
    categories: [],
    reviews: [],
    tagline: null,
    rating: null,
    totalReview: null,
    averageRating: null,
    ratingCount: null,
    labels: [],
  },
  {
    id: "96f97870-ab37-11ec-80e2-005056015f74",
    sku: "233573",
    name: "ANTI-AGE Концентрат рыбьего жира Омега 3 капс 1000 мг х30",
    vendor: "Эвалар",
    dosage: "1000 мг х30",
    country: "Россия",
    model: "капсулы",
    activeIngredient: null,
    regularPrice: 415,
    salePrice: null,
    inStock: true,
    quantity: 14,
    discount: null,
    images: ["/mockImages/product.png"],
    description: null,
    descriptionSections: [],
    shortDescription: null,
    permalink: null,
    attributes: [],
    groupedProducts: [],
    relatedIds: [],
    tags: [],
    analogs: [],
    variations: [],
    isFeatured: false,
    category: null,
    categories: [],
    reviews: [],
    tagline: null,
    rating: null,
    totalReview: null,
    averageRating: null,
    ratingCount: null,
    labels: [],
  },
  {
    id: "f046673e-aaab-11ec-80e2-005056015f74",
    sku: "233572",
    name: "Цитроплант капс 0,45 г х30",
    vendor: "Эвалар",
    dosage: "0,45 г х30",
    country: "Россия",
    model: "капсулы",
    activeIngredient: null,
    regularPrice: 743,
    salePrice: 994,
    discount: null,
    inStock: true,
    quantity: 44,
    images: ["/mockImages/product.png"],
    description: null,
    descriptionSections: [],
    shortDescription: null,
    permalink: null,
    attributes: [],
    groupedProducts: [],
    relatedIds: [],
    tags: [],
    analogs: [],
    variations: [],
    isFeatured: false,
    category: null,
    categories: [],
    reviews: [],
    tagline: null,
    rating: null,
    totalReview: null,
    averageRating: null,
    ratingCount: null,
    labels: [
      {
        title: "Выгодная цена",
        color: "#6DC47B",
      },
    ],
  },
  {
    id: "40b730a2-289b-11ea-80c8-005056015f74",
    sku: "216817",
    name: "Детримакс Актив, жидкость, 30 млл",
    vendor: "Кертис Хелс Капс",
    dosage: "null",
    country: "Польша",
    model: "жидкость",
    activeIngredient: "Витамин D3",
    regularPrice: 566.16,
    salePrice: null,
    inStock: false,
    discount: null,
    quantity: 0,
    images: ["/mockImages/product.png"],
    description: null,
    descriptionSections: [],
    shortDescription: null,
    permalink: null,
    attributes: [],
    groupedProducts: [],
    relatedIds: [],
    tags: [],
    analogs: [],
    variations: [],
    isFeatured: false,
    category: null,
    categories: [],
    reviews: [],
    tagline: null,
    rating: null,
    totalReview: null,
    averageRating: null,
    ratingCount: null,
    labels: [],
  },
  {
    id: "714270d9-7740-11e1-a26d-d8d385febb70",
    sku: "214702",
    name: "Детский рыбий жир Кусалочка, капсулы 500 мг, 90 шт.",
    vendor: "РеалКапс",
    dosage: "капс. 700мг  х90",
    country: "Россия",
    model: "капсулы жевательные",
    activeIngredient: "Рыбий жир",
    regularPrice: 317.44,
    salePrice: null,
    inStock: false,
    discount: null,
    quantity: 0,
    images: ["/mockImages/product.png"],
    description: null,
    descriptionSections: [],
    shortDescription: null,
    permalink: null,
    attributes: [],
    groupedProducts: [],
    relatedIds: [],
    tags: [],
    analogs: [],
    variations: [],
    isFeatured: false,
    category: null,
    categories: [],
    reviews: [],
    tagline: null,
    rating: null,
    totalReview: null,
    averageRating: null,
    ratingCount: null,
    labels: [],
  },
  {
    id: "3845f48e-9ea7-11eb-80d9-005056015f74",
    sku: "226023",
    name: "Витаферр, капсулы, 30 шт.",
    vendor: "Петровакс Фарм",
    dosage: "375 мг х30",
    country: "Россия",
    model: "капсулы",
    activeIngredient: null,
    regularPrice: 537.77,
    salePrice: null,
    inStock: false,
    discount: null,
    quantity: 0,
    images: ["/mockImages/product.png"],
    description: null,
    descriptionSections: [],
    shortDescription: null,
    permalink: null,
    attributes: [],
    groupedProducts: [],
    relatedIds: [],
    tags: [],
    analogs: [],
    variations: [],
    isFeatured: false,
    category: null,
    categories: [],
    reviews: [],
    tagline: null,
    rating: null,
    totalReview: null,
    averageRating: null,
    ratingCount: null,
    labels: [],
  },
  {
    id: "8dc26b8f-9f6a-11ec-80e2-005056015f74",
    sku: "233565",
    name: "Омега-3 из дикого камчат лосося капс д/взр и дет 1000 мг х42",
    vendor: "Тымлатский Рыбокомбинат",
    dosage: "1000 мг х42",
    country: "Россия",
    model: "капсулы",
    activeIngredient: null,
    regularPrice: 743,
    salePrice: 501,
    inStock: false,
    quantity: 0,
    discount: null,
    images: ["/mockImages/product.png"],
    description: null,
    descriptionSections: [],
    shortDescription: null,
    permalink: null,
    attributes: [],
    groupedProducts: [],
    relatedIds: [],
    tags: [],
    analogs: [],
    variations: [],
    isFeatured: false,
    category: null,
    categories: [],
    reviews: [],
    tagline: null,
    rating: null,
    totalReview: null,
    averageRating: null,
    ratingCount: null,
    labels: [
      {
        title: "Выгодная цена",
        color: "#6DC47B",
      },
    ],
  },
  {
    id: "e933e879-79cd-11df-8089-0026554c8720",
    sku: "214678",
    name: "Комбилипен Табс, таблетки покрыт. плен. об., 60 шт.",
    vendor: "Фармстандарт-УфаВИТА",
    dosage: "х60",
    country: "Россия",
    model: "таблетки в пленочной оболочке",
    activeIngredient: "Бенфотиамин + Пиридоксин + Цианокобаламин",
    regularPrice: 540.28,
    salePrice: null,
    inStock: false,
    discount: null,
    quantity: 0,
    images: ["/mockImages/product.png"],
    description: null,
    descriptionSections: [],
    shortDescription: null,
    permalink: null,
    attributes: [],
    groupedProducts: [],
    relatedIds: [],
    tags: [],
    analogs: [],
    variations: [],
    isFeatured: false,
    category: null,
    categories: [],
    reviews: [],
    tagline: null,
    rating: null,
    totalReview: null,
    averageRating: null,
    ratingCount: null,
    labels: [
      {
        title: "По рецепту",
        color: "#FF785A",
      },
    ],
  },
];
