import { UserOrderT } from "modules/profile/interfaces/userOrders";

export const userOrdersMock: UserOrderT[] = [
  {
    id: "23132123123",
    status: "expected",
    createdOn: "2022-12-26T11:24:42.547Z",
    updatedOn: "2022-12-26T11:24:42.547Z",
    price: 200,
    cancellable: true,
    items: [
      {
        id: "1",
        name: "Фарингосепт, таблетки для рассасывания 10 мг, 20 шт, со вкусом лимона",
        image: "/mockImages/product.png",
        price: 100,
        quantity: 2,
        discount: 5,
        subtotal: 200,
      },
      {
        id: "2",
        name: "Фарингосепт, таблетки для рассасывания 10 мг, 20 шт, со вкусом лимона",
        image: "/mockImages/product.png",
        price: 100,
        quantity: 1,
        discount: 9,
        subtotal: 100,
      },
      {
        id: "3",
        name: "Фарингосепт, таблетки для рассасывания 10 мг, 20 шт, со вкусом лимона",
        image: "/mockImages/product.png",
        price: 100,
        quantity: 1,
        discount: 5,
        subtotal: 200,
      },
      {
        id: "4",
        name: "Фарингосепт, таблетки для рассасывания 10 мг, 20 шт, со вкусом лимона",
        image: "/mockImages/product.png",
        price: 1,
        quantity: 1,
        discount: 1,
        subtotal: 1,
      },
      {
        id: "5",
        name: "Фарингосепт, таблетки для рассасывания 10 мг, 20 шт, со вкусом лимона",
        image: "/mockImages/product.png",
        price: 1,
        quantity: 1,
        discount: 1,
        subtotal: 1,
      },
    ],
    deliveryDetails: {
      title: "string",
      details: "Планета здоровья, ул. Саянская, д. 11А",
      buyerName: "Денисов Денис",
      buyerPhone: "89211234567",
      buyerEmail: "string",
      deliveryDate: "2022-12-26",
      deliveryTime: "string",
    },
    paymentDetails: {
      paid: true,
      paymentComment: "test comment",
    },
  },
  {
    id: "12312312321",
    status: "going",
    createdOn: "2022-12-26T11:24:42.547Z",
    updatedOn: "2022-12-26T11:24:42.547Z",
    price: 200,
    cancellable: true,
    items: [
      {
        id: Math.floor(Math.random() * 5400).toString(32),
        name: "string",
        image: "/mockImages/product.png",
        price: 1,
        quantity: 1,
        discount: 1,
        subtotal: 1,
      },
      {
        id: Math.floor(Math.random() * 5400).toString(32),
        name: "string",
        image: "/mockImages/product.png",
        price: 1,
        quantity: 1,
        discount: 1,
        subtotal: 1,
      },
    ],
    deliveryDetails: {
      title: "string",
      details: "Планета здоровья, ул. Саянская, д. 11А",
      buyerName: "Денисов Денис",
      buyerPhone: "89211234567",
      buyerEmail: "string",
      deliveryDate: "2022-12-26",
      deliveryTime: "string",
    },
    paymentDetails: {
      paid: true,
      paymentComment: "test comment",
    },
  },
  {
    id: "421499",
    status: "delivered",
    createdOn: "2022-12-26T11:24:42.547Z",
    updatedOn: "2022-12-26T11:24:42.547Z",
    price: 200,
    cancellable: true,
    items: [
      {
        id: Math.floor(Math.random() * 5400).toString(32),
        name: "string",
        image: "/mockImages/product.png",
        price: 10,
        quantity: 20,
        discount: 5,
        subtotal: 30,
      },
      {
        id: Math.floor(Math.random() * 5400).toString(32),
        name: "string",
        image: "/mockImages/product.png",
        price: 1,
        quantity: 1,
        discount: 1,
        subtotal: 1,
      },
      {
        id: Math.floor(Math.random() * 5400).toString(32),
        name: "string",
        image: "/mockImages/product.png",
        price: 1,
        quantity: 1,
        discount: 1,
        subtotal: 1,
      },
      {
        id: Math.floor(Math.random() * 5400).toString(32),
        name: "string",
        image: "/mockImages/product.png",
        price: 1,
        quantity: 1,
        discount: 1,
        subtotal: 1,
      },
    ],
    deliveryDetails: {
      title: "string",
      details: "Планета здоровья, ул. Саянская, д. 11А",
      buyerName: "Денисов Денис",
      buyerPhone: "string",
      buyerEmail: "string",
      deliveryDate: "2022-12-26",
      deliveryTime: "string",
    },
    paymentDetails: {
      paid: true,
      paymentComment: "test comment",
    },
  },
];
