apiVersion: v1
kind: Service
metadata:
  name: website-service
  labels:
    app: website-service
    service: website-service
spec:
  type: ClusterIP
  ports:
    - name: http-website
      port: 80
      targetPort: 3000
  selector:
    app.kubernetes.io/name: website
    app.kubernetes.io/instance: website
    app: website