export enum ComparisonOperatorEnum {
  Equal = "Equal",
  NotEqual = "NotEqual",
  LessThan = "LessThan",
  LessThanOrEqual = "LessThanOrEqual",
  GreaterThan = "GreaterThan",
  GreaterThanOrEqual = "GreaterThanOrEqual",
  Like = "Like",
  LikeAny = "LikeAny",
  NotLike = "NotLike",
  RegexMatch = "RegexMatch",
  Enumeration = "Enumeration",
  NotEnumeration = "NotEnumeration",
  StartWith = "StartWith",
  EndWith = "EndWith",
  NotStartWith = "NotStartWith",
  NotEndWith = "NotEndWith",
  Between = "Between",
  NotBetween = "NotBetween",
  Empty = "Empty",
  NotEmpty = "NotEmpty",
  Parent = "Parent",
  Null = "Null",
  NotNull = "NotNull",
}
