export enum TreeType {
  BIRCH = "береза.jpg",
  OAK = "дуб 2.jpg",
  WILLOW = "ива.jpg",
  CHESTNUT = "каштан.jpg",
  CEDAR = "кедр.jpg",
  CYPRESS = "кипарис 2.jpg",
  MAPLE = "клен 2.jpg",
  ALDER = "ольха.jpg",
  ASPEN = "осина.jpg",
  PALM = "пальма 2.jpg",
  SYCAMORE = "платан.jpg",
  PLUM = "слива.jpg",
  PINE = "сосна.jpg",
  POPLAR = "тополь.jpg",
  EUCALYPTUS = "эвкалипт.jpg",
  APPLE = "яблоня.jpg",
  LINDEN = "липа.jpg",
  PEAR = "груша.jpg",
  obrabotki_ot_koroeda_kakie_derevya_ewe_mozhno_spasti2 = "obrabotki_ot_koroeda_kakie_derevya_ewe_mozhno_spasti2.jpg",
}
