# Install dependencies only when needed
FROM node:14-alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
ARG NEXT_PUBLIC_BACK_URL
RUN echo $NEXT_PUBLIC_BACK_URL
ENV NEXT_PUBLIC_BACK_URL=$NEXT_PUBLIC_BACK_URL
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Rebuild the source code only when needed
FROM node:14-alpine AS builder
RUN echo $NEXT_PUBLIC_BACK_URL
ENV NEXT_PUBLIC_BACK_URL=$NEXT_PUBLIC_BACK_URL
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE 4100
CMD ["npm", "run", "dev"]
